IF COL_LENGTH('LeaseTerms', 'PropertyId') IS NULL
BEGIN
    ALTER TABLE LeaseTerms
    ADD PropertyId INT NOT NULL
END

IF NOT EXISTS (SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'LeaseTerms' AND CONSTRAINT_NAME = 'FK_LeaseTerms_Properties')
BEGIN
	ALTER TABLE [dbo].[LeaseTerms] WITH CHECK ADD CONSTRAINT [FK_LeaseTerms_Properties] FOREIGN KEY([PropertyId]) REFERENCES [dbo].[Property] ([Id])
END