
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PropertyManagementTool.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Bill
{

    public int BillId { get; set; }

    public decimal Amount { get; set; }

    public int PropertyOwnerId { get; set; }

    public int ResposiblePartyId { get; set; }

    public Nullable<int> TaskId { get; set; }

    public Nullable<int> PropertyId { get; set; }

    public Nullable<int> TenantId { get; set; }

    public System.DateTime DueDate { get; set; }

    public System.DateTime DateCreated { get; set; }

    public string Description { get; set; }

    public int CategoryId { get; set; }

    public int BillStatusId { get; set; }



    public virtual BillStatu BillStatu { get; set; }

    public virtual Owner Owner { get; set; }

    public virtual Property Property { get; set; }

    public virtual ResposibleParty ResposibleParty { get; set; }

    public virtual Tenant Tenant { get; set; }

    public virtual ExpenseIncomeCategory ExpenseIncomeCategory { get; set; }

}

}
