
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PropertyManagementTool.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class LeaseTerm
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LeaseTerm()
    {

        this.LeaseApplications = new HashSet<LeaseApplication>();

    }


    public int LeaseTermId { get; set; }

    public double Duration { get; set; }

    public decimal MonthlyRent { get; set; }

    public string Description { get; set; }

    public int PropertyId { get; set; }

    public bool IsActive { get; set; }



    public virtual Property Property { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LeaseApplication> LeaseApplications { get; set; }

}

}
