
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PropertyManagementTool.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Lease
{

    public int LeaseId { get; set; }

    public int PropertyId { get; set; }

    public int TenantId { get; set; }

    public double Duration { get; set; }

    public decimal InitialDeposit { get; set; }

    public string InitialDepositDescription { get; set; }

    public decimal MonthlyRent { get; set; }

    public System.DateTime StartDate { get; set; }

    public System.DateTime EndDate { get; set; }

    public int LeaseStatusId { get; set; }



    public virtual Property Property { get; set; }

    public virtual Tenant Tenant { get; set; }

    public virtual LeaseStatu LeaseStatu { get; set; }

}

}
