
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PropertyManagementTool.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Transaction
{

    public int TransactionId { get; set; }

    public decimal Amount { get; set; }

    public int PropertyOwnerId { get; set; }

    public System.DateTime DateCreated { get; set; }

    public Nullable<int> BillId { get; set; }

    public int CategoryId { get; set; }

    public Nullable<int> PropertyId { get; set; }



    public virtual Owner Owner { get; set; }

    public virtual Property Property { get; set; }

    public virtual ExpenseIncomeCategory ExpenseIncomeCategory { get; set; }

}

}
